/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kTE5cJfrn6i
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function AboutUsMain() {
  return (
    <div className="flex flex-col">
      <section className="bg-primary py-20 md:py-32">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-16 items-center">
            <div className="space-y-4">
              <h1 className="text-4xl md:text-6xl font-bold text-primary-foreground">
                Discover the Joy of Mathematics
              </h1>
              <p className="text-lg md:text-xl text-primary-foreground">
                Explore our curated collection of mathematics books for all levels.
              </p>
              <Link
                href="/products"
                className="inline-flex items-center justify-center rounded-md bg-secondary px-6 py-3 text-sm font-medium text-secondary-foreground shadow-sm transition-colors hover:bg-secondary/90 focus:outline-none focus:ring-2 focus:ring-secondary focus:ring-offset-2"
                prefetch={false}
              >
                Shop Now
              </Link>
            </div>
            <div className="hidden md:block">
              <img src="/placeholder.svg" width={500} height={400} alt="Mathematics Books" className="rounded-lg" />
            </div>
          </div>
        </div>
      </section>
      <section className="py-20 md:py-32">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-16 items-center">
            <div>
              <img src="/placeholder.svg" width={500} height={400} alt="About Us" className="rounded-lg mx-auto" />
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">About Us</h2>
              <p className="text-muted-foreground">
                At our e-commerce store, we are passionate about mathematics and believe in the power of education. Our
                mission is to provide high-quality mathematics books that inspire and empower learners of all ages and
                skill levels.
              </p>
              <p className="text-muted-foreground">
                Founded in 2015, our company has grown to become a trusted source for mathematics enthusiasts around the
                world. We carefully curate our selection of books, ensuring that each title offers unique insights and
                valuable learning opportunities.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
