/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qffc9Brqpdn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function FeedbackForm() {
  return (
    <section className="m-auto w-full sm:w-full md:w-3/4 lg:w-2/3 pt-12 md:pt-24 lg:pt-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-6">
          <div className="space-y-2 text-center">
            <h2 className="text-3xl font-bold">Give us your feedback</h2>
            <p className="text-muted-foreground">Help us improve our book selection and services.</p>
          </div>
          <form className="space-y-4">
            <div className="grid gap-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="Enter your email" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="feedback">Feedback</Label>
              <Textarea id="feedback" placeholder="Share your thoughts and suggestions" className="min-h-[120px]" />
            </div>
            <div className="flex justify-end">
              <Button type="submit">Submit Feedback</Button>
            </div>
          </form>
        </div>
      </div>
    </section>
  )
}
