/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CshBIi9KNLR
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Policies() {
  return (
    <>
    <section id="privacy-policy" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Privacy Policy</h1>
          <p className="mt-2 text-muted-foreground">Effective Date: July 16, 2024</p>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Collection</h2>
          <p className="text-muted-foreground">
            We collect certain personal information from you when you visit our website, make a purchase, or interact
            with us. This may include your name, email address, billing and shipping addresses, payment information, and
            any other information you provide to us.
          </p>
          <p className="text-muted-foreground">
            We also collect certain information automatically, such as your IP address, browser type, device
            information, and browsing activity on our website.
          </p>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Usage</h2>
          <p className="text-muted-foreground">
            We use the information we collect to process your orders, provide customer support, improve our website and
            products, and for marketing and advertising purposes.
          </p>
          <p className="text-muted-foreground">
            We may share your information with third-party service providers who assist us in operating our business,
            such as payment processors, shipping carriers, and analytics providers. We require these third parties to
            maintain the confidentiality and security of your information.
          </p>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Your Rights</h2>
          <p className="text-muted-foreground">
            You have the right to access, correct, or delete your personal information. You can also opt-out of
            receiving marketing communications from us.
          </p>
          <p className="text-muted-foreground">
            If you have any questions or concerns about our privacy practices, please contact us at privacy@example.com.
          </p>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Changes to this Policy</h2>
          <p className="text-muted-foreground">
            We may update this Privacy Policy from time to time. Any changes will be effective immediately upon posting
            the updated policy on our website.
          </p>
        </div>
      </div>
    </section>

    <section id="terms-and-conditions" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Terms and Conditions</h1>
          <p className="mt-2 text-muted-foreground">By using our website and services, you agree to our terms and conditions. These terms outline the rules and guidelines for using our platform, as well as your rights and responsibilities as a customer. Some key points in our terms and conditions include:</p>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Intellectual Property</h2>
          <p className="text-muted-foreground">
          All content and materials on our website are the property of Acme Math Books and are protected by copyright and other intellectual property laws.
          </p>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Acceptable Use</h2>
          <p className="text-muted-foreground">
          You agree to use our website and services only for lawful purposes and in a way that does not infringe on the rights of others or restrict or inhibit anyone else's use and enjoyment of the website.
          </p>
          
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Limitation of Liability</h2>
          <p className="text-muted-foreground">
          We are not responsible for any damages or losses related to your use of our website or services, except as required by applicable law.
          </p>
          
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Governing Law</h2>
          <p className="text-muted-foreground">
          These terms and conditions are governed by the laws of the state of California, and any disputes will be resolved in the courts of that jurisdiction.
          </p>
        </div>
      </div>
    </section>

    <section id="return-policy" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Return Policy</h1>
          <p className="mt-2 text-muted-foreground">At StudyMaxx, we stand behind the quality of our products. If you are not satisfied with your purchase, you can return it within 30 days for a full refund. To initiate a return, please contact our customer service team with your order information and the reason for the return. We will provide you with a prepaid return label and instructions on how to send the item back to us.

Please note that items must be in new, unused condition to be eligible for a refund. We cannot accept returns on custom-ordered or personalized items. If you have any questions about our return policy, please don't hesitate to reach out.</p>
        </div>
      </div>
    </section>

    <section id="refund-policy" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Refund Policy</h1>
          <p className="mt-2 text-muted-foreground">At StudyMaxx, we are committed to providing a hassle-free refund process. If you are not satisfied with your purchase for any reason, you can request a full refund within 30 days of the delivery date. To initiate a refund, please contact our customer service team with your order information and the reason for the refund request.

We will process your refund as soon as possible, typically within 5-7 business days. Please note that refunds may take longer to appear on your statement, depending on your bank's processing time. If you have any questions or concerns about our refund policy, please don't hesitate to reach out.</p>
        </div>
      </div>
    </section>

    <section id="shipping-policy" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Shipping Policy</h1>
          <p className="mt-2 text-muted-foreground">At StudyMaxx, we strive to provide fast and reliable shipping to our customers. We offer several shipping options, including standard ground shipping, expedited shipping, and international shipping.

Standard ground shipping typically takes 5-7 business days for delivery within the contiguous United States. Expedited shipping options are available for faster delivery, with 2-day and overnight shipping available for an additional fee.

For international orders, shipping times may vary depending on the destination and the selected shipping method. We recommend allowing 10-14 business days for international deliveries. Please note that customers are responsible for any customs fees or taxes associated with international shipments.

If you have any questions or concerns about our shipping policy, please don't hesitate to contact our customer service team.</p>
        </div>
      </div>
    </section>

    <section id="cancellation-policy" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Cancellation Policy</h1>
          <p className="mt-2 text-muted-foreground">At StudyMaxx, we understand that sometimes plans change, and you may need to cancel an order. We are happy to accommodate cancellation requests, as long as the order has not yet been shipped.

To cancel an order, please contact our customer service team as soon as possible. We will process the cancellation and issue a full refund to the original payment method. Please note that we cannot cancel orders that have already been shipped.

If you have any questions or concerns about our cancellation policy, please don't hesitate to reach out.</p>
        </div>
      </div>
    </section>

    <section id="disclaimer" className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Disclaimer</h1>
          <p className="mt-2 text-muted-foreground">The information and materials provided on our website are for general informational purposes only. We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose.

Any reliance you place on such information is therefore strictly at your own risk. In no event will we be liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</p>
        </div>
      </div>
    </section>
    </>
  )
}
