/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BayVDMcjtNp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ShareButton } from "./share-button"
import { useRouter } from "next/navigation"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"

export function ProductDetails(props: { isModal: boolean }) {
  const router = useRouter();
  const { isModal } = props;
  return (
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div className="grid gap-4">
        <img
          src="/placeholder.svg"
          alt="Book Cover"
          width={600}
          height={800}
          className="rounded-lg border w-full aspect-[3/4] object-cover shadow-lg hover:shadow-xl transition-shadow duration-300"
        />
        
      </div>
      <div className="grid gap-4 md:gap-8">
        <div className="grid gap-2">
          <h1 className="text-3xl font-bold text-primary">The Alchemist</h1>
          <div className="flex flex-row justify-between">
            <div className="flex items-center gap-2 text-muted-foreground">
              <span>by</span>
              <Link href="#" className="text-primary hover:underline underline-offset-4" prefetch={false}>
                Paulo Coelho
              </Link>
              <ShareButton link="http://localhost:3000/products/5" />
            </div>
            {isModal && <TooltipProvider delayDuration={100}>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button className="rounded-full p-2" variant="outline">
                      <img src="/full-screen.svg" width={18} className="cursor-pointer" onClick={() => router.push('/products/5')} />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Open in full-screen mode</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
            } 
          </div>
        </div>
        <div className="grid gap-2">
          <div className="flex items-center justify-start gap-4">
            <div className="text-2xl font-bold text-primary">&#8377;14.99</div>
            <div className="text-xl font-bold text-muted-foreground line-through">&#8377;19.99</div>
            <Badge variant="outline">
              25% OFF
            </Badge>
          </div>
          <Button size="lg" variant="outline" className="mr-auto border-primary text-primary hover:bg-primary hover:text-primary-foreground transition-colors mt-4">Preview</Button>
          {/* <div className="grid sm:grid-cols-2 gap-4">
            <div className="grid gap-1">
              <div className="flex justify-start items-center gap-1">
                <img src="/book.svg" width={22} />
                <div className="text-sm font-semibold">Level/Class</div>
              </div>
              <div className="text-sm text-muted-foreground ml-[25px]">High School</div>
            </div>
            <div className="grid gap-1">
              <div className="flex justify-start items-center gap-1">
                <img src="/subject.svg" width={22} />
                <div className="text-sm font-semibold">Subject</div>
              </div>
              <div className="text-sm text-muted-foreground ml-[25px]">Fiction</div>
            </div>
            <div className="grid gap-1">
              <div className="flex justify-start items-center gap-1">
                <img src="/board.svg" width={22} />
                <div className="text-sm font-semibold">Board</div>
              </div>
              <div className="text-sm text-muted-foreground ml-[25px]">CBSE</div>
            </div>
            <div className="grid gap-1">
              <div className="flex justify-start items-center gap-1">
                <img src="/exam.svg" width={22} />
                <div className="text-sm font-semibold">Exam</div>
              </div>
              <div className="text-sm text-muted-foreground ml-[25px]">-</div>
            </div>
          </div> */}
        </div>
        {/* <div className="grid gap-2">
          <div className="flex justify-start items-center gap-1">
            <img src="/keyword.svg" width={22} />
            <div className="text-sm font-semibold">Keywords</div>
          </div>
          <div className="flex flex-wrap gap-2 ml-[25px]">
            <Badge variant="outline">
              Fiction
            </Badge>
            <Badge variant="outline">
              Adventure
            </Badge>
            <Badge variant="outline">
              Self-Discovery
            </Badge>
          </div>
        </div> */}
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/language.svg" width={22} />
              <div className="text-sm font-semibold">Language</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">English</div>
          </div>
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/isbn.svg" width={22} />
              <div className="text-sm font-semibold">ISBN</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">978-0-06-251595-9</div>
          </div>
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/pages.svg" width={22} />
              <div className="text-sm font-semibold">Pages</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">208</div>
          </div>
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/year.svg" width={22} />
              <div className="text-sm font-semibold">Year</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">1988</div>
          </div>
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/size.svg" width={22} />
              <div className="text-sm font-semibold">Size</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">5 x 8 inches</div>
          </div>
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/paperback.svg" width={22} />
              <div className="text-sm font-semibold">Binding</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">Paperback</div>
          </div>
          <div className="grid gap-1">
            <div className="flex justify-start items-center gap-1">
              <img src="/category.svg" width={22} /> 
              <div className="text-sm font-semibold">Category</div>
            </div>
            <div className="text-sm text-muted-foreground ml-[25px]">Fiction</div>
          </div>
        </div>
        
        <div className="grid grid-cols-2 lg:flex gap-2">
          <Button size="lg" className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
            <ShoppingCartIcon className="mr-2 h-4 w-4" />
            Add to Cart
          </Button>
          <Button size="lg" className="flex-1 bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
            <img src="/rupee.svg" width={20}/>
            Buy Now
          </Button>
          <Button
            size="lg"
            variant="outline"
            className="flex-1 border-primary text-primary hover:bg-primary hover:text-primary-foreground transition-colors"
          >
            <HeartIcon className="mr-2 h-4 w-4" />
            Add to Wishlist
          </Button>
        </div>
        
      </div>
    </div>
  )
}

function HeartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function ShoppingCartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
