/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/V91lAZHbnA2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Reviews() {
  
  return (
    <div className="max-w-6xl mx-auto px-4 md:px-6 pt-8">
      <div className="grid gap-8">
        <div>
          <h2 className="text-2xl font-bold mb-4">Leave a Review</h2>
          <form className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="review">Review</Label>
              <Textarea id="review" placeholder="Write your review" rows={4} />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="rating">Rating</Label>
                <div className="flex items-center gap-2">
                  <StarIcon className="w-5 h-5 fill-primary cursor-pointer" />
                  <StarIcon className="w-5 h-5 fill-primary cursor-pointer" />
                  <StarIcon className="w-5 h-5 fill-primary cursor-pointer" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground cursor-pointer" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground cursor-pointer" />
                </div>
              </div>
            </div>
            <Button type="submit" className="justify-self-end">
              Submit Review
            </Button>
          </form>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Customer Reviews</h2>
          <div className="grid gap-6">
            <div className="flex gap-4">
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">John Doe</div>
                  <div className="text-xs text-muted-foreground">@johndoe</div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-0.5">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  </div>
                  <div className="text-xs text-muted-foreground">2 days ago</div>
                </div>
                <div className="text-sm leading-loose text-muted-foreground">
                  The product is amazing! It has exceeded my expectations in every way. Highly recommended.
                </div>
              </div>
            </div>
            <div className="flex gap-4">
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">Jane Smith</div>
                  <div className="text-xs text-muted-foreground">@janesmith</div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-0.5">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  </div>
                  <div className="text-xs text-muted-foreground">1 week ago</div>
                </div>
                <div className="text-sm leading-loose text-muted-foreground">
                  I love this product! It has made my life so much easier. The customer service is also top-notch.
                </div>
              </div>
            </div>
            <div className="flex gap-4">
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">Alex Johnson</div>
                  <div className="text-xs text-muted-foreground">@alexjohnson</div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-0.5">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  </div>
                  <div className="text-xs text-muted-foreground">3 weeks ago</div>
                </div>
                <div className="text-sm leading-loose text-muted-foreground">
                  The product is good, but I had some issues with the installation. The customer support was helpful in
                  resolving the problem.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
