import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { NavBar } from "@/components/component/nav-bar";
import { Footer } from "@/components/component/footer";

export const metadata: Metadata = {
  title: "StudyMaxx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <CookiesProvider >
        <AuthProvider>
          <StoreProvider>
          <NavBar />
          <body className={inter.className}>
          
            <main>
            
              {children}
           
              <Toaster />
            </main>
          
          </body>
          <Footer />
          </StoreProvider>
        </AuthProvider>
        </CookiesProvider>
      </html>
  );
}
