import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "StudyMaxx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <CookiesProvider >
        <AuthProvider>
          <body className={inter.className}>
          <StoreProvider>
            <main>
              {children}
              <Toaster />
            </main>
          </StoreProvider>
          </body>
        </AuthProvider>
        </CookiesProvider>
      </html>
  );
}
