import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { NavBar } from "@/components/component/nav-bar";
import { Footer } from "@/components/component/footer";
import { UserProvider } from "@/context/UserContext";
import { BookProvider } from "@/context/BookContext";
import { QRProvider } from "@/context/QRProvider";

export const metadata: Metadata = {
  title: "StudyMaxx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
                  
                    <body className={inter.className}>
      <CookiesProvider>
        <AuthProvider>
          <StoreProvider>
            <UserProvider>
              <BookProvider>
                <QRProvider>
                  
                    <NavBar />
                      <main>
                        {children}
                        <Toaster />
                      </main>
                      <Footer />
                    
                </QRProvider>
              </BookProvider>
            </UserProvider>
          </StoreProvider>
        </AuthProvider>
      </CookiesProvider>
      </body>
                    
                  </html>
    </>
  );
}
